_wandb:
    value:
        cli_version: 0.21.1
        e:
            r82dw0c8kvls5d8md6naymifebpzmsc9:
                args:
                    - --config
                    - configs/distilbert_partial.yaml
                    - --sample
                    - --sample-size
                    - "100"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "482717536256"
                        used: "393947439104"
                email: mattm@itu.dk
                executable: C:\Users\matma\anaconda3\envs\ADVNLPfinal\python.exe
                git:
                    commit: 405ccb3a520df2d54696756188e2f5db743a64df
                    remote: https://github.com/MalipieroMattia/AVDNLP_final_project.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-df6c91b7-d5aa-d25b-13d9-ead4c63f6fd2
                host: Asus_Mattia
                memory:
                    total: "16342159360"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\matma\Desktop\ITU\NLP\AVDNLP_final_project\main.py
                python: CPython 3.12.12
                root: C:\Users\matma\Desktop\ITU\NLP\AVDNLP_final_project
                startedAt: "2025-11-16T08:53:58.032425Z"
                writerId: r82dw0c8kvls5d8md6naymifebpzmsc9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "3":
                - 2
                - 13
                - 15
                - 61
            "4": 3.12.12
            "5": 0.21.1
            "6": 4.57.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
